// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number):Promise<string>;

export function GetVersion():Promise<Record<string, string>>;
