// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:boolean,arg10:boolean,arg11:boolean,arg12:boolean,arg13:boolean,arg14:boolean):Promise<string>;

export function GetVersion():Promise<Record<string, string>>;
